# Kunskapskontroll 1 - Del 2

### Kapitel 1 - Koduppgift 11
Förklara varför test_size=0.2 och sedan test_size=0.25 ger proportionerna 60-20-20.

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression

# Genreate mockdata 
X, y = make_regression(n_samples=1000, n_features=3, noise=0.1, random_state=42)

# Split the data into training and testing sets
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 20% for testing, 80% for training

# Second split the training data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.25, random_state=42)# 0.25 x 0.8 = 0.2

print("Total amount of observations: ", len(X))
print("Training: ", len(X_train))
print("Validation: ", len(X_val))
print("Testing: ", len(X_test))

Total amount of observations:  1000
Training:  600
Validation:  200
Testing:  200

Först delas datan upp så det blir 20% till test, då blir ju 80% kvar. Därefter ska valideringsdata skapas och då behöver man ta 25% av den återstående 80% av datamängden vilket faktiskt är 20% av hela datamängden. Vilket leder till 60-20-20 propportionerna på uppdelningen av datamängden, det vill säga 60% träning, 20% validering och 20% test.

### Kapitel 2 - koduppgift 8

In [2]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from joblib import dump, load

X, y = make_regression(n_samples=20000, n_features=3, noise=0.1) # Generate mock data
model = LinearRegression().fit(X, y) # Model learns the relationship between X and y
dump(model, "linear_model.joblib") # Save the model to a file
model_loaded = load("linear_model.joblib") # Load the model from the file
print(model_loaded.predict(X[:5])) # Predict the first 5 samples using the loaded model

[ -7.33325075 -56.24300269 -79.07863052 -74.49805254  99.2891791 ]

Först skapas syntetisk data med hjälp av funktionen make_regression i Scikit-learn. Därefter skapas en modell som tränas för att lära sig relationen mellan X och y.
Den tränade modellen sparas sedan som en fil på datorn med hjälp av dump(). Därefter laddas modellen in igen från filen och används för att göra prediktioner, där resultatet för de första datapunkterna skrivs ut.

Det är viktigt att kunna spara modellen eftersom det gör att man kan använda en redan tränad modell utan att behöva träna om den varje gång. Träning av en modell kan vara tidskrävande och resureskrävande beroende på hur avancerad modellen är. 
Genom att spara modellen kan den enkelt laddas in och användas för att göra predektioner på ny data.

### Kaptiel 2 - koduppgift 9

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
# 9a
df = pd.read_csv("data_01.csv") # Load the dataset from a CSV file into a DataFrame
print(df.head())

         x1        x2        x3        x4        x5      target
0  0.743487  1.072825  1.332911 -1.244771  0.344978  220.173943
1  0.835264  0.202184  0.966480  0.745883 -0.033773  175.873929
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224 -162.270054
3  1.210186  1.685258 -0.394123  0.719024 -2.166585  165.930461
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473   43.250511

In [4]:
#9b
X = df.drop("target", axis=1) # Features (all columns except 'target')
y = df["target"] # Target variable

In [5]:
# 9c
# Split the data into training and testing sets
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 20% for testing, 80% for training

# Second split the training data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.1875, random_state=42) # 0.1875 x 0.8 = 0.15, so we end up with 15% validation, 65% training, and 20% testing

In [6]:
# 9d
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

lin_reg = LinearRegression()
tree_reg = DecisionTreeRegressor(random_state=42)

lin_reg.fit(X_train, y_train) # Train the linear regression model on the training data
tree_reg.fit(X_train, y_train) # Train the decision tree regression model on the training data

DecisionTreeRegressor(random_state=42)

In [7]:
# 9e
from sklearn.metrics import root_mean_squared_error

rmse_linreg = root_mean_squared_error(y_val,
lin_reg.predict(X_val)) # Calculate RMSE for linear regression on the validation set
rmse_tree = root_mean_squared_error(y_val, tree_reg.predict(X_val))
print(f"RMSE on validation - Linear Regression:{rmse_linreg:.2f}")
print(f"RMSE on validation - Decision Tree: {rmse_tree:.2f}") # Calculate RMSE for decision tree regression on the validation set

RMSE on validation - Linear Regression:3.32
RMSE on validation - Decision Tree: 96.01

In [8]:
# 9e
if rmse_linreg < rmse_tree:
  best_model = LinearRegression()
  best_model_name = "Linear Regression"
else:
  best_model = DecisionTreeRegressor(random_state=42)
  best_model_name = "Decision Tree Regression"
  
print("The best model is: ", best_model_name)

The best model is:  Linear Regression

In [9]:
# 9f
best_model.fit(X_train_full, y_train_full)

LinearRegression()

In [10]:
# 9g
rmse_test = root_mean_squared_error(y_test,
best_model.predict(X_test))
print(f"Best model based on validation: {best_model_name}")
print(f"RMSE on test data: {rmse_test:.2f}")

Best model based on validation: Linear Regression
RMSE on test data: 3.37

In [11]:
# 9h
best_model.fit(X, y)

LinearRegression()

### Kapitel 2 - kodfråga 10

In [12]:
# 10a
from sklearn.svm import LinearSVR
from sklearn.model_selection import cross_validate
import numpy as np
df = pd.read_csv("salary_dataset.csv") # Load the dataset from a CSV file into a DataFrame
print(df.head())

   YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [13]:
#10a
X = df[["YearsExperience"]]
y = df["Salary"]

In [14]:
# 10b
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split the data into training and testing sets

In [15]:
# 10c
lr = LinearRegression()
svm = LinearSVR()

In [16]:
# 10c and d
cv_lr = cross_validate(lr, X_train, y_train, cv=5, scoring="neg_root_mean_squared_error") # Perform 5-fold cross-validation for linear regression
cv_svm = cross_validate(svm, X_train, y_train, cv=5, scoring="neg_root_mean_squared_error") # Perform 5-fold cross-validation for linear SVM regression

print(cv_lr.keys()) # Print the keys of the cross-validation results for linear regression
print(cv_svm.keys()) # Print the keys of the cross-validation results for linear SVM regression

print(cv_lr["test_score"]) # Print the test scores (negative RMSE) for linear regression
print(cv_svm["test_score"]) # Print the test scores (negative RMSE) for linear SVM regression

dict_keys(['fit_time', 'score_time', 'test_score'])
dict_keys(['fit_time', 'score_time', 'test_score'])
[-4550.08341777 -6393.62938648 -5697.35170249 -1868.75051151
 -7956.20096673]
[-80999.65296915 -69027.22167427 -71902.92574937 -95757.86792996
 -70501.90276706]

In [17]:
# 10d
if np.mean(cv_lr["test_score"]) > np.mean(cv_svm["test_score"]):
  print("The best model is Linear Regression")
elif np.mean(cv_lr["test_score"]) == np.mean(cv_svm["test_score"]):
  print("The models have the same mean test score, we can choose either one as the best model")
else: 
  print("The best model is support vector machine regression")

The best model is Linear Regression

### Kapitel 2 - koduppgift 11

In [18]:
import seaborn as sns
df = sns.load_dataset("mpg")
print(df.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite
3          70    usa              amc rebel sst
4          70    usa                ford torino

In [19]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [20]:
df = df.dropna()

In [21]:
df = df.drop(columns=["name"])
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [22]:
df = pd.get_dummies(df, columns=["origin"], drop_first=True)

In [23]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,18.0,8,307.0,130.0,3504,12.0,70,False,True
1,15.0,8,350.0,165.0,3693,11.5,70,False,True
2,18.0,8,318.0,150.0,3436,11.0,70,False,True
3,16.0,8,304.0,150.0,3433,12.0,70,False,True
4,17.0,8,302.0,140.0,3449,10.5,70,False,True

In [24]:
X = df.drop("mpg", axis=1)
y = df["mpg"]

In [25]:
X_train, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 20% for testing, 80% for training

In [26]:
model = LinearRegression()
model.fit(X_train, y_train_full)

LinearRegression()

In [27]:
y_pred = model.predict(X_test)

In [28]:
rmse = root_mean_squared_error(y_test, model.predict(X_test))
print("RMSE: ", rmse)

RMSE:  3.2561140968473956

### Kaptel 2 - Koduppgift 12

In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

housing_org = pd.read_csv("housing.csv")
housing_org.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [30]:
housing_org.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [31]:
housing_org.iloc[:, :6].head() # Show the first 6 columns of the dataset to get an overview of the features and target variable

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population
0,-122.23,37.88,41.0,880.0,129.0,322.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0

In [32]:
housing_org.iloc[:, :5].head() # Show the first 5 columns of the dataset to get an overview of the features and target variable

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms
0    -122.23     37.88                41.0        880.0           129.0
1    -122.22     37.86                21.0       7099.0          1106.0
2    -122.24     37.85                52.0       1467.0           190.0
3    -122.25     37.85                52.0       1274.0           235.0
4    -122.25     37.85                52.0       1627.0           280.0

In [33]:
housing_org['ocean_proximity'].value_counts() # Show the unique values and their counts in the 'ocean_proximity' column to understand the distribution of this categorical feature

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [34]:
housing = housing_org[housing_org['ocean_proximity'] != "ISLAND"]
housing['ocean_proximity'].value_counts() # Show the unique values and their counts in the 'ocean_proximity' column after removing rows with "ISLAND" to understand the distribution of this categorical feature

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
Name: count, dtype: int64

In [35]:
housing.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [36]:
housing = pd.get_dummies(housing, columns=["ocean_proximity"], dtype=int, prefix="dmy") # Convert the 'ocean_proximity' categorical variable into dummy/indicator variables for modeling

In [37]:
housing.iloc[[1, 200, 1000, 1850, 5000], 9:] # Show the dummy variables for the 'ocean_proximity' column for specific rows to verify that the encoding was done correctly

      dmy_<1H OCEAN  dmy_INLAND  dmy_NEAR BAY  dmy_NEAR OCEAN
1                 0           0             1               0
200               0           0             1               0
1000              0           1             0               0
1850              0           0             0               1
5000              1           0             0               0

In [38]:
train_full, test = train_test_split(housing, test_size=0.2, random_state=40) # Split the data into training and testing sets
train, val = train_test_split(train_full, test_size=0.25, random_state=36) # Split the training data into training and validation sets

In [39]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12381 entries, 12054 to 14298
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           12381 non-null  float64
 1   latitude            12381 non-null  float64
 2   housing_median_age  12381 non-null  float64
 3   total_rooms         12381 non-null  float64
 4   total_bedrooms      12261 non-null  float64
 5   population          12381 non-null  float64
 6   households          12381 non-null  float64
 7   median_income       12381 non-null  float64
 8   median_house_value  12381 non-null  float64
 9   dmy_<1H OCEAN       12381 non-null  int64
 10  dmy_INLAND          12381 non-null  int64
 11  dmy_NEAR BAY        12381 non-null  int64
 12  dmy_NEAR OCEAN      12381 non-null  int64
dtypes: float64(9), int64(4)
memory usage: 1.3 MB

In [40]:
train = train.dropna() 
train.info() # Check for missing values and drop rows with missing values in the training set

<class 'pandas.core.frame.DataFrame'>
Index: 12261 entries, 12054 to 14298
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           12261 non-null  float64
 1   latitude            12261 non-null  float64
 2   housing_median_age  12261 non-null  float64
 3   total_rooms         12261 non-null  float64
 4   total_bedrooms      12261 non-null  float64
 5   population          12261 non-null  float64
 6   households          12261 non-null  float64
 7   median_income       12261 non-null  float64
 8   median_house_value  12261 non-null  float64
 9   dmy_<1H OCEAN       12261 non-null  int64
 10  dmy_INLAND          12261 non-null  int64
 11  dmy_NEAR BAY        12261 non-null  int64
 12  dmy_NEAR OCEAN      12261 non-null  int64
dtypes: float64(9), int64(4)
memory usage: 1.3 MB

In [41]:
val = val.dropna()
test = test.dropna() # Drop rows with missing values in the validation and test sets to ensure that we can evaluate the model on complete data

In [42]:
X_train_full = train_full.drop(columns=["median_house_value"])
y_train_full = train_full["median_house_value"]

X_train, y_train = train.drop(columns=["median_house_value"]), train["median_house_value"]
X_val, y_val = val.drop(columns=["median_house_value"]), val["median_house_value"]
X_test, y_test = test.drop(columns=["median_house_value"]), test["median_house_value"]

In [ ]:
# Check the shapes of the training, validation, and testing sets to ensure they are correctly split
print(X_train.shape)
print(y_train.shape)

(12261, 12)
(12261,)

In [44]:
# Train a linear regression model on the training data
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [45]:
import time 
from sklearn.ensemble import RandomForestRegressor

In [46]:
start_time = time.time() # Start the timer to measure the time taken for grid search

rf = RandomForestRegressor()
hyperparam_grid = {'max_depth': [10, 20, None], 'n_estimators': [50, 100, 200], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2]}
grid_search = GridSearchCV(estimator=rf, param_grid=hyperparam_grid, cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1) # Perform grid search with 5-fold cross-validation to find the best hyperparameters for the random forest regressor, using negative RMSE as the scoring metric and utilizing all available CPU cores for parallel processing
grid_search.fit(X_train, y_train) # Fit the grid search to the training data to find the best hyperparameters for the random forest regressor
best_rf = grid_search.best_estimator_
print("Best hyperparameters: ", grid_search.best_params_)
end_time = time.time()
print("Time taken for grid search: ", end_time - start_time, " seconds") # Print the time taken for the grid search to find the best hyperparameters for the random forest regressor

Best hyperparameters:  {'max_depth': None, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200}
Time taken for grid search:  191.15505003929138  seconds

In [47]:
# Train the best random forest model on the full training data (training + validation) to utilize all available data for training before evaluating on the test set
y_pred_val = best_rf.predict(X_val)
rmse_val = root_mean_squared_error(y_val, y_pred_val)

print("Validation RMSE:", rmse_val)

Validation RMSE: 49316.67538613588

In [48]:
# Train the best random forest model on the full training data (training + validation) to utilize all available data for training before evaluating on the test set
y_pred_test = best_rf.predict(X_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test) 

print("Test RMSE:", rmse_test)

Test RMSE: 49425.46419985618